### ISSUE TITLE
Logo For T-Remote

### ISSUE THREAD

**Issue by zularizal** [cmhernandezdel/t-remote#1]
Hi @cmhernandezdel ,  I'm a graphic designer. I like your project, I want to contribute by creating a free logo for your project. What do you think?

**Comment by cmhernandezdel** [comment]
For sure! Any help is appreciated!

What do you have in mind?

**Comment by zularizal** [comment]
Okay. I will create a logo for this project and display some proposal logos in the next reply.

**Comment by cmhernandezdel** [comment]
Okay, thank you!

I'll put you into contributors section in the docs. Looking forward for your ideas!

**Comment by zularizal** [comment]
Hi @cmhernandezdel , Hi, this is the design logo for your project. This logo is inspired by the letter T, the remote icon, the presentation board icon and the control button icon.

I provide several color choices that you might like. Which color do you like?

If there is something you want to change, let me know.

![bitmap](https://user-images.githubusercontent.com/38547278/55861731-2fb89900-5ba1-11e9-95e7-24d392cbb36b.png)

**Comment by cmhernandezdel** [comment]
I LOVE the blue one (1). Great work, thank you so much!

I'll include it in next update along with your username in colaborators.

Thank you again!

**Comment by zularizal** [comment]
Okay, I will make a pull request

**Comment by zularizal** [comment]
Hi @cmhernandezdel , I have sent a pull request. @cmhernandezdel 

And also I have uploaded the logo to the drive. Check this link.
https://drive.google.com/open?id=1FOLQSde3_U_mBhmeFHFtz5C-mLz71MLb

**Comment by cmhernandezdel** [comment]
Perfect, I have merged your pull request and will add you to the contributors file in next update (hope it's release).

I'll close the issue already. If you have any problems or suggestions, just open a new one.

Again, thank you very much.
